import { Copy, Check } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";

const generatedCode = `import pandas as pd
import numpy as np
from talib import RSI, SMA

def strategy(data: pd.DataFrame) -> pd.DataFrame:
    """
    Strategy: Buy when RSI < 30 and price above 200 SMA
    Generated by Tradeky AI
    """
    
    # Calculate indicators
    data['rsi'] = RSI(data['close'], timeperiod=14)
    data['sma_200'] = SMA(data['close'], timeperiod=200)
    
    # Generate signals
    data['signal'] = 0
    
    # Buy condition: RSI < 30 AND close > SMA 200
    buy_condition = (data['rsi'] < 30) & (data['close'] > data['sma_200'])
    data.loc[buy_condition, 'signal'] = 1
    
    # Sell condition: RSI > 70
    sell_condition = data['rsi'] > 70
    data.loc[sell_condition, 'signal'] = -1
    
    # Calculate positions
    data['position'] = data['signal'].replace(0, np.nan).ffill().fillna(0)
    
    # Calculate returns
    data['strategy_returns'] = data['position'].shift(1) * data['close'].pct_change()
    data['cumulative_returns'] = (1 + data['strategy_returns']).cumprod()
    
    return data

# Backtest configuration
INITIAL_CAPITAL = 100000
COMMISSION = 0.001  # 0.1% per trade
SLIPPAGE = 0.0005   # 0.05% slippage

if __name__ == "__main__":
    # Load data
    data = pd.read_csv('RELIANCE.csv', parse_dates=['date'], index_col='date')
    
    # Run strategy
    results = strategy(data)
    
    # Print summary statistics
    print(f"Total Return: {(results['cumulative_returns'].iloc[-1] - 1) * 100:.2f}%")
    print(f"Sharpe Ratio: {results['strategy_returns'].mean() / results['strategy_returns'].std() * np.sqrt(252):.2f}")
`;

export function CodeViewer() {
  const [copied, setCopied] = useState(false);
  
  const handleCopy = () => {
    navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  
  return (
    <div className="h-full flex flex-col">
      <div className="flex items-center justify-between px-4 py-2 bg-muted/30 border-b border-border">
        <div className="flex items-center gap-2">
          <span className="text-xs font-mono text-muted-foreground">strategy.py</span>
          <span className="text-xs px-1.5 py-0.5 rounded bg-profit/20 text-profit">Python</span>
        </div>
        
        <Button 
          variant="ghost" 
          size="sm" 
          onClick={handleCopy}
          className="h-7 text-xs"
        >
          {copied ? (
            <>
              <Check className="w-3 h-3 mr-1" />
              Copied
            </>
          ) : (
            <>
              <Copy className="w-3 h-3 mr-1" />
              Copy
            </>
          )}
        </Button>
      </div>
      
      <div className="flex-1 overflow-auto p-4 bg-background">
        <pre className="font-mono text-sm text-foreground leading-relaxed">
          {generatedCode.split('\n').map((line, index) => (
            <div key={index} className="flex">
              <span className="w-10 flex-shrink-0 text-muted-foreground/50 select-none text-right pr-4">
                {index + 1}
              </span>
              <code className={
                line.trimStart().startsWith('#') || line.trimStart().startsWith('"""') || line.includes('"""')
                  ? 'text-muted-foreground'
                  : line.includes('def ') || line.includes('import ') || line.includes('from ')
                    ? 'text-primary'
                    : line.includes("'") || line.includes('"')
                      ? 'text-profit'
                      : ''
              }>
                {line || ' '}
              </code>
            </div>
          ))}
        </pre>
      </div>
    </div>
  );
}
